import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/multiple-use/navigation-bar/PageHeader.js";
import Footer from "@/components/multiple-use/footer/Footer.js";
import { ThemeProvider } from "@/app-context/ThemeContext";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "CBS Research Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins || inter} suppressHydrationWarning={true}>
        <ThemeProvider>
          <PageHeader />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
